spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "Hello again!"

---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "Hello  from the production profile!"